env:
  global:
  - GH_REF: github.com/xing-zhi/travis-token-test.git
language: node
node: 8.0.0

install:
- npm i
script:
- git checkout master
- cd examples
- git init
- git remote add origin git@github.com:xing-zhi/travis-token-test.git
- git add .
- git commit -m 'Update examples'
- git push -u -f origin master:gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_e61430108bdf_key -iv $encrypted_e61430108bdf_iv
  -in travis_rsa.enc -out ~\/.ssh/travis_rsa -d
- ls -l ~/.ssh/*
- chmod 600 ~/.ssh/travis_rsa
- sudo cp .travis/ssh_config /etc/ssh/ssh_config
- sudo chmod 755 /etc/ssh/ssh_config
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/travis_rsa
- git config --global user.name "TravisBot"
- git config --global user.email "travis@example.com"
