env:
  global:
    - GH_REF: github.com/xing-zhi/travis-token-test.git
    - secure: k7wlzwIHBVQFV48PBR66R5CPA4SEo1s17fiyBW+KhUv2uPwyShKaD8mG6zYBnMn7enj8w2TSj0dTrjiLpIJSHNCXGn1Usalu5btEgI1kbtH5BT7PT533znloivzIW3JQksdsHpbbUFoBHViLHOG+1lu9vwkRO4X1zTBKVaBLtCcWBKWERqCT+BU5YSOvVFBIgSpb+qlmujV1sX137RmeohlB/YaaZE5A34HSwitrxEcHHTi9CqNBUu7MW1h6mkApGrb23ZeRYU95aEE9NUdu10apZJcTpAqQUuZjau/bnv1yW52U5aErkGvCTLanRvS7S6jGDDkaKzenNART4Ds/qNv6K5WgrZ40C3dxgOvOmPH0AEn6zXoifGGl02YWY0vrnH4mc/1hwDmi8DfMyrxIt0dggAq3ssFghL8PVybqoL9r7ARxU0ARmRNwGGo+fcJ7PksPwUMsId25jcvhAO3m6CFuw49jS4F8fbafSlZ3FC1D9rDBI2V9x1+eLogM7WTZRP1h3CE/8ErsIDkErI24M9bcXjvju7IWkmIWemiWZprdJPeGFl7NyCQ9PqBFYrduxoCKe7KWfIk9/MMXmk56hcY+7DlTLmAPUl6JrONgyyu9SkgbsA62m7/m0Oeka67+njLimxzZkuCZL0VsD0QoduGzVoIFxEfWkc6gn/y6zfY=

language: node
node: stable
install:
- npm i
script:
- git remote rm origin
- git remote add origin https://xing-zhi:${GH_TOKEN}@${GH_REF}
- git checkout master
- npm run build
- git add .
- git branch
- git status
- git commit -m 'build'
- git status
- git push -u origin master
- cd examples
- git init
- git remote add origin https://xing-zhi:${GH_TOKEN}@${GH_REF}
- git add .
- git commit -m 'Update examples'
- git push -u -f origin master:gh-pages
